### ISSUE TITLE
×「すべてのオブジェクトはObjectを継承している」○「すべてのオブジェクトはObject.prototypeを継承している」

### ISSUE THREAD

**Issue by yassh** [uhyo/uhyohyo.net#1]
http://uhyohyo.net/javascript/9_3.html には「すべてのオブジェクトはObjectを継承している」と書かれていますが、正しくは「すべてのオブジェクトは**Object.prototype**を継承している」ですよね？

`{}`は[Obejct](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)のメソッドを持っていません。

```js
console.log({}.assign); // => undefined
```

一方、[Object.prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype)のメソッドは持っています。

```js
console.log({}.toString); // => ƒ toString() { [native code] }
```

**Comment by uhyo** [comment]
ありがとうございます。確かにその箇所での「継承」という言葉の使い方はおかしいですね。
「すべてのオブジェクトはObject.prototypeを継承している」という言い回しは正しいですが、
そのページにおける「継承」の意味と違ってきてしまいます。
正しくかつ分かりやすくなるように修正しようと思います。
