### ISSUE TITLE
適当なオブジェクトに勝手に値を結び付けたい場合の例

### ISSUE THREAD

**Issue by osimakazuya** [uhyo/uhyohyo.net#10]
https://uhyohyo.net/javascript/16_4.html

> const myhiddensymbol=Symbol();  //実際はグローバル変数にせずにどこかに隠しておく
> 
> function saveValueInObject(obj,value){
>   obj[myhiddensymbol]=value;
> }
> function getValueFromObject(obj){
>   return obj[myhiddensymbol]=value;
> }

getValueFromObjectの方は
 **=value**
が必要無い？ような気がします 勘違いならすいません・・

**Comment by uhyo** [comment]
ありがとうございます！
ご指摘の通りです。
