### ISSUE TITLE
IE11はWeakMapをサポートしている

### ISSUE THREAD

**Issue by yassh** [uhyo/uhyohyo.net#2]
IE11はWeakMapをサポートしています。
https://msdn.microsoft.com/ja-jp/library/dn251546(v=vs.94).aspx

※WeakSetはサポートしていません。
https://msdn.microsoft.com/ja-jp/library/dn911720(v=vs.94).aspx

https://uhyohyo.net/javascript/16_1.html
この記事の冒頭は、ES2015の多くの機能はIE11で使えないから注意せよという趣旨だと思うのですが、IE11はWeakMapをサポートしていないという誤解を与えそうです。

**Comment by uhyo** [comment]
ありがとうございます。趣旨はそういうことです。
誤解を与えないように加筆修正します。
