### ISSUE TITLE
最新のHTMLの仕様では、thead,tbody,tfootの順でなければならない

### ISSUE THREAD

**Issue by yassh** [uhyo/uhyohyo.net#3]
https://uhyohyo.net/javascript/2_9.html には

> また、tableの中に書く順は、thead,tfoot,tbodyの順だと決まっています（ただし、HTML5においてはtfootをtbodyの後に書く書き方も許可されました）。

と書かれていますが、最新のHTMLの仕様では、**thead,tbody,tfoot**の順でないといけません。

> In this order: optionally a caption element, followed by zero or more colgroup elements, followed optionally by a thead element, followed by either zero or more tbody elements or one or more tr elements, followed optionally by a tfoot element, optionally intermixed with one or more script-supporting elements.

― [HTML 5.1 2nd Edition - 4.9.1. The table element](https://www.w3.org/TR/html/tabular-data.html#elementdef-table)

> In this order: optionally a caption element, followed by zero or more colgroup elements, followed optionally by a thead element, followed by either zero or more tbody elements or one or more tr elements, followed optionally by a tfoot element, optionally intermixed with one or more script-supporting elements.

― [HTML Living Standard - 4.9.1 The table element](https://html.spec.whatwg.org/multipage/tables.html#the-table-element)

**Comment by uhyo** [comment]
ありがとうございます。順番がいつのまにか完全に変わっていたのは知りませんでした。
