### ISSUE TITLE
×「議論が煮詰まっている」○「議論が行き詰まっている」

### ISSUE THREAD

**Issue by yassh** [uhyo/uhyohyo.net#4]
https://uhyohyo.net/javascript/16_22.html

> ...しかし、時として議論はなかなかまとまらず先に進まないものです。とはいえ、議論が煮詰まっているからといってECMAScriptのバージョンアップが停滞するのはやはりよろしくありません。

「議論が煮詰まる」とは、議論に決着が付きそうになることです。この文脈では、「議論が煮詰まっている」ではなく「議論が行き詰まっている」が正しいと思います。

**Comment by uhyo** [comment]
その通りですね。ありがとうございます。
