### ISSUE TITLE
「きららファンタジアのガチャをまとめるやつ」のデザイン崩れ

### ISSUE THREAD

**Issue by arcturu** [uhyo/uhyohyo.net#5]
ガチャをまとめるやつでアイコンサイズを最大または上から二番目にすると添付画像のように崩れます。
環境: iPhone 6s
UA: 
![db805172-54e8-4d4e-befe-a43cf3df678b](https://user-images.githubusercontent.com/7508715/35784757-6d85fb64-0a5e-11e8-8f5b-f4bc89da77cf.png)
Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1

**Comment by uhyo** [comment]
Thanks!
